import React,{useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';
const API=import.meta.env.VITE_API_URL||'http://127.0.0.1:8000';const H=t=>({Authorization:'Bearer '+t,'Content-Type':'application/json'});
function App(){const[t,setT]=useState(localStorage.token||'');const[f,setF]=useState({username:'',password:''});const[tab,setTab]=useState('login');const[d,setD]=useState(null);const[products,setProducts]=useState([]);const[cart,setCart]=useState([]);const[p,setP]=useState({sku:'',name:'',price:10,stock:10,reorder_level:5});const[msg,setMsg]=useState('');
async function auth(){const x=await(await fetch(API+'/auth/'+tab,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)})).json();if(x.access_token){localStorage.token=x.access_token;setT(x.access_token)}else setMsg(x.detail||'Account created. Please sign in.')}
async function load(){const h={Authorization:'Bearer '+t};const[a,b]=await Promise.all([fetch(API+'/dashboard',{headers:h}),fetch(API+'/products',{headers:h})]);setD(await a.json());setProducts(await b.json())}
async function add(){const x=await(await fetch(API+'/products',{method:'POST',headers:H(t),body:JSON.stringify(p)})).json();if(x.detail)return setMsg(x.detail);setMsg('Product saved');load()}
async function checkout(){if(!cart.length)return;const x=await(await fetch(API+'/checkout',{method:'POST',headers:H(t),body:JSON.stringify({items:cart.map(x=>({sku:x.sku,quantity:x.quantity}))})})).json();if(x.detail)return setMsg(x.detail);setMsg('Sale completed. Receipt #'+x.id+' — Total '+x.total);setCart([]);load()}
function addCart(x){setCart(v=>{const e=v.find(y=>y.sku===x.sku);return e?v.map(y=>y.sku===x.sku?{...y,quantity:y.quantity+1}:y):[...v,{...x,quantity:1}]})}
if(!t)return <main><section className="auth"><h1>Inventory & POS System</h1><p>Manage products, stock, checkout and sales.</p><div className="row"><button onClick={()=>setTab('login')}>Login</button><button onClick={()=>setTab('register')}>Register</button></div><input placeholder="Username" onChange={e=>setF({...f,username:e.target.value})}/><input type="password" placeholder="Password" onChange={e=>setF({...f,password:e.target.value})}/><button className="primary" onClick={auth}>{tab==='login'?'Sign in':'Create account'}</button><p>{msg}</p></section></main>;
return <main><section><div className="row"><div><h1>Inventory & POS Dashboard</h1><p>Live inventory and checkout workspace.</p></div><button onClick={()=>{localStorage.clear();setT('')}}>Logout</button></div><button className="primary" onClick={load}>Refresh KPIs</button>{d&&<div className="cards"><div className="card">Products<br/><b>{d.products}</b></div><div className="card">Sales<br/><b>{d.sales}</b></div><div className="card">Revenue<br/><b>{d.revenue}</b></div><div className="card">Low Stock<br/><b>{d.low_stock.length}</b></div></div>}<div className="forms"><div className="panel"><h3>Add / Update Product</h3><input placeholder="SKU" onChange={e=>setP({...p,sku:e.target.value})}/><input placeholder="Product name" onChange={e=>setP({...p,name:e.target.value})}/><input type="number" placeholder="Price" value={p.price} onChange={e=>setP({...p,price:Number(e.target.value)})}/><input type="number" placeholder="Stock" value={p.stock} onChange={e=>setP({...p,stock:Number(e.target.value)})}/><input type="number" placeholder="Reorder level" value={p.reorder_level} onChange={e=>setP({...p,reorder_level:Number(e.target.value)})}/><button className="primary" onClick={add}>Save Product</button></div><div className="panel"><h3>Cart</h3><div className="cart">{cart.length?cart.map(x=><div key={x.sku}>{x.name} × {x.quantity} — {(x.price*x.quantity).toFixed(2)}</div>):'Cart is empty'}</div><button className="primary" onClick={checkout}>Checkout</button></div></div><h3>Products</h3><table><thead><tr><th>SKU</th><th>Name</th><th>Price</th><th>Stock</th><th>Action</th></tr></thead><tbody>{products.map(x=><tr key={x.sku}><td>{x.sku}</td><td>{x.name}</td><td>{x.price}</td><td>{x.stock}</td><td><button onClick={()=>addCart(x)}>Add to cart</button></td></tr>)}</tbody></table><p>{msg}</p><a href={API+'/docs'} target="_blank">API Documentation →</a></section></main>}
createRoot(document.getElementById('root')).render(<App/>);